### Site info:
title: David's Blog
tagline: Do what you love to do .
author: David Hsu
email: davidh83110@gmail.com
description: "Linux and NetSeurity." # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "Linux , NetSeurity , unix , owasp , bash , network"
baseurl: "//blog.davidh83110.com" # the subpath of your site, e.g. /blog/
url: "//blog.davidh83110.com" # the base hostname & protocol for your site
locale: en_US

### Personal info and site tools info:
twitter_username: davidh83110
github_username:  davidh83110
facebook_username: ben12567
instagram_username: ben12567
disqus_shortname: davidh83110
favicon:     "/images/favicon.ico"
aboutme: Hi, I am David from Taiwan. # these are shown on aboutme-sidebar.
aboutme_photo: "/images/avator.jpg" # your photo.
google_analytics_key: UA-85468802-1 # put YOUR key here to enable tracking! (blank to disable)


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown where ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English (en), Chinese (cn), Japanese (jp), Polish (pl), Korean (kr) and Russian (ru) 

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      #Blogroll: "Blogroll"
      Categories: "Categories"
      #Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "下一頁"
      Next: "上一頁"
      PostedInCategories: "目錄："
      Taggedwith: "｜ 標籤"
      PostDate: "發佈時間："
      Google_search: "Site Search"
      Home: "Blog"
      Homepage: "Home"
      About: "About"
      #Guestbook: "Guestbook"
      Subscribe: "RSS"
    zh:
      Aboutme: "關於我"
      Archives: "存擋"
      Blogroll: "良師益友"        
      Categories: "目錄分類"    
      Copyright_Notice: "版權聲明"
      Recent_Posts: "近期文章"
      Tags: "標籤" 
      Previous: "前一頁"
      Next: "後一頁"
      PostedInCategories: "目錄:"   
      Taggedwith: "| 標籤:"
      PostDate: "| 發佈時間: "
      Google_search: "站內搜索"
      Home: "首頁"
      About: "關於我"
      Guestbook: "留言"
      Subscribe: "訂閱我"
    jp:
      Aboutme: "著者"
      Archives: "アーカイブ"
      Blogroll: "ブログロール"
      Categories: "カテゴリー"
      Copyright_Notice: "著作権表示"
      Recent_Posts: "最近の投稿"
      Tags: "タグ"
      Previous: "前の記事"
      Next: "次の記事"
      PostedInCategories: "カテゴリー："
      Taggedwith: "| タグ："
      PostDate: "| 投稿日時: "
      Google_search: "サイト内検索"
      Home: "ホーム"
      About: "このブログについて"
      Guestbook: "メッセージ"
      Subscribe: "購読"
    pl:
      Aboutme: "O mnie"
      Archives: "Archiwum"
      Blogroll: "Odnośniki"
      Categories: "Kategorie"
      Copyright_Notice: "Prawa autorskie"
      Recent_Posts: "Najnowsze wpisy"
      Tags: "Tagi"
      Previous: "Starsze"
      Next: "Nowsze"
      PostedInCategories: "Kategoria"
      Taggedwith: "tagi"
      PostDate: "on "
      Google_search: "Wyszukiwarka"
      Home: "Strona główna"
      About: "O mnie"
      Guestbook: "Księga gości"
      Subscribe: "Subskrypcja"
    kr:
      Aboutme: "저자 소개"
      Archives: "모든 게시물"
      Blogroll: "참조 링크"
      Categories: "카테고리"
      Copyright_Notice: "저작권"
      Recent_Posts: "최근 게시물"
      Tags: "태그"
      Previous: "이전 게시물"
      Next: "다음 게시물"
      PostedInCategories: "카테고리: "
      Taggedwith: "태그: "
      PostDate: "작성일: "
      Google_search: "게시물 검색"
      Home: "홈"
      About: "소개"
      Guestbook: "방명록"
      Subscribe: "구독하기"
    ru:
      Aboutme: "Обо мне" # = 'About me'
      Archives: "Архив"
      Blogroll: "Ссылки" # = 'Links'
      Categories: "Разделы"
      Copyright_Notice: "Авторские права"
      Recent_Posts: "Свежие посты"
      Tags: "Теги"
      Previous: "Предыдущий пост"          # = 'Previous post'
      Next: "Следующий пост"               # = 'Next post'
      PostedInCategories: "Опубликовано в" # = 'Posted in'
      Taggedwith: "с тегами"
      PostDate: ""
      Google_search: "Поиск на Google"
      Home: "Домой"
      About: "О блоге"            # = 'About blog'
      Guestbook: "Гостевая книга"
      Subscribe: "Подписаться"

### your Blogroll info, only name can shown on the page.

#Blogroll:
#      - name: David's Blog
#        href: https://blog.davidh83110.com
#        title: Tech blog
#      - name: author's website
#        href: http://yulijia.net/
#        title: Lijia Yu's website


### Build settings
markdown: kramdown
#highlighter: pygments
kramdown:
        input: GFM
        syntax_highlighter: rouge
gems: [jekyll-paginate]
paginate: 5
excerpt_separator: <!-- more -->
